name: 'GitHub Actions CloudFlare2DNSPod Bot'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'run cf2dns'
        env:
          CONFIG: ${{ secrets.CONFIG }}
          DOMAINS: ${{ secrets.DOMAINS }}
          PROVIDER: ${{ secrets.PROVIDER }}
        run: python cf2dns_actions.py
